spring:
  datasource:
    url: jdbc:mysql://47.111.112.220:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 19961001@Zmm
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.macro.mall: debug
    com.macro.mall.demo.service.FeignAdminService: debug
